add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$buf\
$direnv\
$env_var\
$sudo\
$jobs\
$status\
$os\
$container\
$shell\
$character"""

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'
