after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-m = 'focus left'
alt-n = 'focus down'
alt-e = 'focus up'
alt-i = 'focus right'

alt-shift-m = 'move left'
alt-shift-n = 'move down'
alt-shift-e = 'move up'
alt-shift-i = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

f19 = ['exec-and-forget open /Applications/Brave\ Browser.app', 'workspace ψ']
f20 = ['exec-and-forget open /Applications/WezTerm.app', 'workspace λ']
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

f15 = [
  'move-node-to-workspace --wrap-around prev',
  'workspace --wrap-around prev',
]
f16 = [
  'move-node-to-workspace --wrap-around next',
  'workspace --wrap-around next',
]
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

f17 = 'workspace --wrap-around prev'
f18 = 'workspace --wrap-around next'

alt-shift-semicolon = 'mode service'

alt-f = 'fullscreen'
alt-r = 'flatten-workspace-tree'
alt-w = 'close'
alt-shift-w = 'close-all-windows-but-current'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = [
  'layout floating tiling',
  'mode main',
]
backspace = ['close-all-windows-but-current', 'mode main']
m = ['join-with left', 'mode main']
n = ['join-with down', 'mode main']
e = ['join-with up', 'mode main']
i = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['move-node-to-workspace λ']

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = ['move-node-to-workspace ψ']
